theme: minima

header_pages:
  - about.md
  - academic-cv.md
  
site.author.name: Jess Yao

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jesslyao" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }
