theme: minima

header_pages:
  - about.md
  - academic-cv.md
  
author:
  name: John Smith
  email: "john.smith@foobar.com"

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jesslyao" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }
